/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "[ Tutorial ]": "[ 教程 ]",
    "About": "关于",
    "Adventure": "冒险",
    "Artifice": "技巧",
    "Attack": "攻击",
    "Attack:": "攻击：",
    "Attack: 1": "攻击：1",
    "Attack: 5, Defense: 0, Strength: 5": "攻击：5，防御：0，力量：5",
    "Attack: undefined, Defense: undefined, Strength: undefined": "攻击：未定义，防御：未定义，强度：未定义",
    "Autosave every 60s": "每 60 秒自动保存一次",
    "Bank": "银行",
    "Boots:": "靴子：",
    "Chest:": "胸部：",
    "Coins: 0": "硬币: 0",
    "Cooked Chicken": "煮熟的鸡",
    "Defense": "防御",
    "Equipment": "装备",
    "Farm": "农场",
    "Gloves:": "手套：",
    "Helm:": "头盔：",
    "Hit:": "打：",
    "Hitpoints: 10": "生命值：10",
    "Lapidary: 1": "宝石工坊：1",
    "Legs:": "腿：",
    "Max Hit:": "最大命中：",
    "Me": "我",
    "Modifiers": "修饰符",
    "Offhand:": "副手：",
    "Ratings": "收视率",
    "Skills": "技能",
    "Stone Axe": "石斧",
    "Stone Pick": "石镐",
    "Strength": "力量",
    "This is the [ Bank ] tab where you can interact with all the items you have gathered in the game.": "这是 [ 银行 ] 选项卡，您可以在其中与您在游戏中收集的所有物品进行互动。",
    "Training Style:": "训练风格：",
    "Training Sword": "训练剑",
    "Try equipping your Stone Pick for the next part of the tutorial!": "尝试为教程的下一部分装备你的石镐！",
    "Weapon:": "武器：",
    "Welcome to Artifice!": "欢迎来到 技巧放置！",
    "Welcome!": "欢迎！",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "Game Saved!": "游戏已保存！",
    "( This tutorial can be found in the [ About ] tab )": "（本教程可在【关于】标签中找到）",
    "[ Adventure ]": "[ 冒险 ]",
    "[ Artifice ]": "[ 技巧 ]",
    "[ Combat ]": "[ 战斗 ]",
    "[ Mining ]": "[ 采矿 ]",
    "[ Smithing ]": "[ 锻造 ]",
    "Also, certain weapons are better for training certain stats.": "此外，某些武器更适合训练某些统计数据。",
    "and mining some Copper!": "并开采一些铜！",
    "and with stronger weapons and armor you can kill greater foes.": "有了更强大的武器和盔甲，你可以杀死更强大的敌人。",
    "Attack: Accuracy, Strength: Max hit, and Defense: Evasion": "攻击：精准，力量：最大命中，防御：回避",
    "now go see if you can slay all the monsters!": "现在去看看你是否可以杀死所有的怪物！",
    "Now that you have your Pick equipped try navigating to the [ Mining ] tab on the left": "现在你已经装备好 Pick，尝试导航到左侧的 [ 采矿 ] 选项卡",
    "On the [ Smithing ] tab try smithing a Copper Bar with the ore you just gathered.": "在 [ 锻造 ] 选项卡上尝试用您刚刚收集的矿石锻造铜锭。",
    "Once you have your bar you can then select your very first weapon": "一旦你有了你的酒吧，你就可以选择你的第一把武器",
    "or tool to smith!": "或锻造工具！",
    "That's all for the time being,": "暂时就这些了",
    "The [ Artifice ] tab is where you make your gear even more powerful.": "[ 技巧 ] 选项卡是让你的装备更加强大的地方。",
    "The adventure tab is where you can kill monsters for loot.": "冒险选项卡是您可以杀死怪物以获得战利品的地方。",
    "The speed is determined by how strong your tool is!": "速度取决于你的工具有多强大！",
    "There is a special place called the Grove where animals drop hides": "有一个特殊的地方叫做格罗夫，动物掉落兽皮",
    "There is no level cap, but cost scales quickly.": "没有等级上限，但成本增长很快。",
    "Try collecting 2 Bars and upgrading the weapon you just made!": "尝试收集 2 个锭并升级您刚刚制作的武器！",
    "Upgrading your equipment as high as you can is the basis of this game.": "尽可能高地升级你的装备是这个游戏的基础。",
    "which can be crafted into armor and upgraded the same as weapons!": "可以制作成盔甲并像武器一样升级！",
    "With stronger tools you gather materials and level up skills faster,": "使用更强大的工具，您可以更快地收集材料和提升技能，",
    "You can train different combat styles by selecting them on the left.": "您可以通过在左侧选择它们来训练不同的战斗风格。",
    "You will need very strong tools, weapons, and armor to advance.": "你需要非常强大的工具、武器和盔甲才能前进。",
    "Tutorial": "教程",
    "Weapon Speed": "武器速度",
    "Gather Speed": "收集速度",
    "Training Sword:": "训练剑术：",
    "Something went wrong.": "出错了。",
    "You may need to refresh.": "您可能需要刷新一下页面。",
    "Battle": "战斗",
    "Boneyard": "埋骨地",
    "Chicken": "鸡",
    "City": "城市",
    "Dragon": "龙",
    "Eat": "吃",
    "Grove": "树林",
    "Man": "男人",
    "option Boneyard, selected.": "选项 Boneyard，已选中。",
    "option City, selected.": "选项城市，选择。",
    "option Grove, selected.": "选项 Grove，已选中。",
    "option Volcano, selected.": "选项火山，选择。",
    "Select is focused ,type to refine list, press Down to open the menu,": "选择焦点，键入以优化列表，按向下键打开菜单，",
    "Select...": "选择...",
    "Spooky Ghost": "阴森森的幽灵",
    "Stag": "雄鹿",
    "Thief": "小偷",
    "Volcano": "火山",
    "Alumite": "氧化铝",
    "Bear": "熊",
    "Beef": "牛肉",
    "Boar": "公猪",
    "Boots": "靴子",
    "Chest": "胸部",
    "Chop": "砍",
    "Coal": "煤炭",
    "Cook": "厨师",
    "Cooking": "烹饪",
    "Copper": "铜",
    "Cow": "奶牛",
    "Cow Leather": "牛皮",
    "Craft": "工艺",
    "Crafting": "制作",
    "Croc": "鳄鱼",
    "Exp:": "经验值：",
    "Fletch": "弗莱奇",
    "Gloves": "手套",
    "Grizzly": "灰熊",
    "Helm": "舵",
    "Iron": "铁",
    "Leather": "皮革",
    "Legs": "腿",
    "Level:": "等级：",
    "Maple": "枫",
    "Mine": "矿",
    "Mining": "采矿",
    "No Items": "无物品",
    "No options": "无选项",
    "Normal": "普通",
    "Normal Plank": "普通板材",
    "Oak": "橡木",
    "Plank": "木板",
    "Raw Chicken": "生鸡肉",
    "Rod": "棒材",
    "Shield": "盾牌",
    "Teak": "柚木",
    "Tin": "锡",
    "Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.": "使用Up和Down选择选项，按Enter选择当前聚焦的选项，按Escape退出菜单，按Tab选择选项并退出菜单。",
    "Venison": "鹿肉",
    "Willow": "柳树",
    "Woodcutting": "伐木",
    "Woodworking": "木材加工",
    "Yew": "红豆杉",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Strength: ": "力量：",
    "Woodcutting ": "伐木 ",
    "Woodcutting:": "伐木：",
    "Woodworking ": "木头加工 ",
    "Woodworking:": "木头加工：",
    "Mining:": "采矿：",
    "Mining ": "采矿 ",
    "Smithing ": "锻造 ",
    "Smithing:": "锻造：",
    "Crafting ": "制作 ",
    "Crafting: ": "制作：",
    "Cooking ": "烹饪 ",
    "Cooking:": "烹饪：",
    "Defense ": "防御 ",
    "Defense:": "防御：",
    "Fishing:": "钓鱼：",
    "Contact me:": "联系作者：",
    "Developer:": "开发者：",
    "Amount:": "数量：",
    "Chicken:": "鸡：",
    "Artifice ": "技巧 ",
    "Artifice:": "技巧",
    "Raw Chicken:": "生鸡肉：",
    "Normal Log:": "普通木头：",
    "Required:": "要求：",
    "xp: ": "经验：",
    "Cow Hide:": "牛皮：",
    "Burn Rate:": "燃烧速度：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^option Boneyard focused, (.+) of (.+). (.+) results available. Use Up and Down to choose options, press Enter to select the currently focused option, press Escape to exit the menu, press Tab to select the option and exit the menu.$/, 'option Boneyard focused, $1 / $2. $3 results available. 使用Up和Down选择选项，按Enter选择当前聚焦的选项，按Escape退出菜单，按Tab选择选项并退出菜单。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);